### ISSUE TITLE
Error when using levels with spaces

### ISSUE THREAD

**Issue by SpiegelE** [TomKellyGenetics/vioplot#2] opened 2019-05-10 07:35 UTC
The vioplot function provides an error if you are using a data frame with levels, that includes a space. Setting the names argument does also not help. The only thing that helps is changing the levels of the factor variable.
A minimal example is attached.
[Error_spaces.txt](https://github.com/TomKellyGenetics/vioplot/files/3165350/Error_spaces.txt)

**Comment by TomKellyGenetics** [comment] 2019-07-05 06:05
The issue is resolved in the development branch. It will be implemented in the next release. Thanks for reporting it. 

Spaces are enabled in file names and are only removed in variable names internally.

<img width="1312" alt="Screen Shot 2019-07-05 at 15 03 14" src="https://user-images.githubusercontent.com/5493325/60701224-0a37f300-9f36-11e9-8d26-985b0ac010d0.png">

**Closed as completed by TomKellyGenetics** 2019-07-05 06:05 UTC

**Comment by TomKellyGenetics** [comment] 2019-07-06 01:11
This has been implemented in release 0.3.2 submitted to CRAN
