### ISSUE TITLE
Surprising behavior when passing xlim=c(1,2)

### ISSUE THREAD

**Issue by Derek-Jones** [TomKellyGenetics/vioplot#10] opened 2020-03-04 22:44 UTC
Somebody new to `vioplot` might pass an `xlim` argument (this this is available in many other `plot` functions; I did this in one of my plots).

`vioplot(sample(44)) # works as expected`

`vioplot(sample(44), xlim=c(1, 2)) # surprising behavior`

The `xlim` causes a second plot to appear, next the the sample violin plot.

**Comment by mmahmoudian** [comment] 2020-03-05 09:02
I checked with the latest published version:


    par(mfrow = c(1, 2))
    vioplot(sample(40), xlim = c(1,2))
    # changing the xlim to also see how that affects the output
    vioplot(sample(40), xlim = c(1,5))


![image](https://user-images.githubusercontent.com/390889/75964934-bc162d80-5ed0-11ea-8f53-8ff51e5dd8fa.png)

**Comment by Derek-Jones** [comment] 2020-03-05 15:15
This is the behavior I get.

Don't you think it is very surprising?

I was using `wex` to increase the width of the plot, and when it violin plot width exceeded the width of the available x-axis I tried using `xlim` to increase the width of the x-axis (and was really surprised by this behavior).

The `wex` problem is another issue.  It's not involved in the calculation of the estimate width.

**Comment by mmahmoudian** [comment] 2020-03-18 14:25
@Derek-Jones I'm not maintainer of this repo and cannot mark this as bug, but I agree with you that this is unintended behavior

**Comment by Derek-Jones** [comment] 2020-03-18 15:40
@mmahmoudian thanks for agreeing you think the behavior is unintended.

Let's hope that the powers that be agree.

**Comment by TomKellyGenetics** [comment] 2020-06-12 03:36
Since `xlim` is not an input to `vioplot` it is passed to `...` as a data input. Therefore this is not unexpected. These all give the same results.

```
vioplot(sample(40), sample(10))
vioplot(x = sample(40), xlim = sample(10))
x = sample(40)
xlim = sample(10)
vioplot(x, xlim)
```
![test](https://user-images.githubusercontent.com/5493325/84461924-9f944900-aca8-11ea-9cdc-dff39825a6ff.png)

Since other `par` arguments are accepted, is it reasonable set it as NA by default or put a warning here? There is no need to specify `xlim` as this is computed internally.

**Comment by TomKellyGenetics** [comment] 2020-06-12 03:39
Note that as for boxplot the default values are not `c(1, 2)`. These give the same dimensions.

```
vioplot(sample(40), sample(10))
boxplot(sample(40), sample(10), xlim = c(0.5, 2.5))
```

```
vioplot(sample(40))
boxplot(sample(40), xlim = c(0.5, 1.5))
```

I note that boxplot does allow changing these.

**Comment by Derek-Jones** [comment] 2020-06-12 12:17
This is a user interface issue.  Passing `xlim` makes sense with other functions and developers might make the same mistake I did, and get very confused.

**Comment by mmahmoudian** [comment] 2020-06-12 13:14
Of course, there are two ways to address this:
1. similar to many other packages, get the data as a list and expect that anything that is passed through `...` is graphical parameter. (This is not backward compatible, but the only thing users should change is wrapping their input in `list()`)
2. go through the input `dots <- list(...); var_graphical_params %in% names(dots)` and extract the graphical parameters and use the rest as input. (This is more backward compatible, but the issue is that the user gets limited in the names they use for the violins, plus it is more risky to implement)

I personally vote for the first approach.

**Comment by Derek-Jones** [comment] 2020-06-12 13:36
Why not flag the use of `xlim` as suspicious, e.g., give a warning?

The surprising output, plus a warning is a pointer to the fact that the developer has made a mistake.

**Comment by mmahmoudian** [comment] 2020-06-12 13:43
> Why not flag the use of `xlim` as suspicious, e.g., give a warning?

imho because:
1. this solves this specific problem, but it is not a generalizable solution. Meaning the vioplot should handle all such exceptions rather than simply passing them to the graphics functions and let them handle the issue (if there is any issue to be handled).
2. as far as vioplot concerns as a function, there is no problem if user just wants to limit/specify the visible portion of x axis.  one might get an RDS file from somewhere and just want to see item 5 to 10 in the object and technically vioplot should not care as it plots what it is told to, even if they get invisible due to the limit user have specified.

**Comment by Derek-Jones** [comment] 2020-06-12 13:50
Are there lots of people many other silly mistakes?
I might be the only person who made the problem being discussed.  So you could say the issue is not worth addressing.

**Comment by TomKellyGenetics** [comment] 2020-06-15 01:23
I think there is no need for an overhaul of the code. All other graphical parameters (to my knowledge) are handled explicitly.  Thanks for drawing this exception to my attention.

This is a messy way to handle them but it's the simplest way as `...` is already used for data inputs. List input is already support by `vioplot.list` as (S3 methods).

This is package that has been on CRAN for many years. For this reason, I will not make breaking changes that will affect many existing scripts. Thanks for the suggestions (PR's welcome) but I will prioritise backwards compatibility with previous releases absolutely in this case.

Since `graphics::boxplot` and `beanplot::beanplot` both support `xlim` I have added it to the development version of `vioplot` and it will be in the next release. I'd prefer if possible for these functions to have the same input so that you can change a script to use `vioplot` instead of `boxplot` simply by changing the function called. 

I will close this for now but feel free to open a new PR if there are other issues with graphical parameters. If this issues persist, I'm okay to refactor the code, provided that the data and formula inputs are still supported.

**Closed as completed by TomKellyGenetics** 2020-06-15 01:23 UTC
